# Generated by Django 4.2.15 on 2024-08-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='about',
            field=models.TextField(default='No info'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='no-picture.png', upload_to='recipes'),
        ),
    ]
